# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Ui.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(374, 387)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Pre_hight_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Pre_hight_Edit.setGeometry(QtCore.QRect(250, 270, 91, 21))
        self.Pre_hight_Edit.setObjectName("Pre_hight_Edit")
        self.Lift_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Lift_Button.setGeometry(QtCore.QRect(270, 120, 75, 23))
        self.Lift_Button.setObjectName("Lift_Button")
        self.Port_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.Port_lineEdit.setGeometry(QtCore.QRect(60, 49, 151, 21))
        self.Port_lineEdit.setObjectName("Port_lineEdit")
        self.Pre_angel_label = QtWidgets.QLabel(self.centralwidget)
        self.Pre_angel_label.setGeometry(QtCore.QRect(190, 230, 61, 16))
        self.Pre_angel_label.setObjectName("Pre_angel_label")
        self.Angel_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Angel_Edit.setGeometry(QtCore.QRect(80, 230, 91, 20))
        self.Angel_Edit.setObjectName("Angel_Edit")
        self.Stop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Stop_Button.setGeometry(QtCore.QRect(210, 320, 75, 23))
        self.Stop_Button.setObjectName("Stop_Button")
        self.IPlabel = QtWidgets.QLabel(self.centralwidget)
        self.IPlabel.setGeometry(QtCore.QRect(30, 10, 41, 21))
        self.IPlabel.setObjectName("IPlabel")
        self.Disconnect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Disconnect_Button.setGeometry(QtCore.QRect(190, 150, 61, 21))
        self.Disconnect_Button.setObjectName("Disconnect_Button")
        self.Speed_label = QtWidgets.QLabel(self.centralwidget)
        self.Speed_label.setGeometry(QtCore.QRect(20, 190, 61, 20))
        self.Speed_label.setObjectName("Speed_label")
        self.Right_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Right_Button.setGeometry(QtCore.QRect(110, 150, 61, 23))
        self.Right_Button.setObjectName("Right_Button")
        self.Angle_label = QtWidgets.QLabel(self.centralwidget)
        self.Angle_label.setGeometry(QtCore.QRect(20, 230, 54, 12))
        self.Angle_label.setObjectName("Angle_label")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(80, 270, 91, 21))
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.Pre_speed_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Pre_speed_Edit.setGeometry(QtCore.QRect(250, 190, 91, 21))
        self.Pre_speed_Edit.setObjectName("Pre_speed_Edit")
        self.Spedd_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Spedd_Edit.setGeometry(QtCore.QRect(80, 190, 91, 21))
        self.Spedd_Edit.setObjectName("Spedd_Edit")
        self.Connect_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Connect_Button.setGeometry(QtCore.QRect(190, 120, 61, 23))
        self.Connect_Button.setObjectName("Connect_Button")
        self.Pre_angle_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Pre_angle_Edit.setGeometry(QtCore.QRect(250, 230, 91, 20))
        self.Pre_angle_Edit.setObjectName("Pre_angle_Edit")
        self.Recv_textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.Recv_textEdit.setGeometry(QtCore.QRect(220, 10, 121, 101))
        self.Recv_textEdit.setObjectName("Recv_textEdit")
        self.Left_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Left_Button.setGeometry(QtCore.QRect(20, 150, 61, 23))
        self.Left_Button.setObjectName("Left_Button")
        self.IPlabel_2 = QtWidgets.QLabel(self.centralwidget)
        self.IPlabel_2.setGeometry(QtCore.QRect(20, 50, 41, 21))
        self.IPlabel_2.setObjectName("IPlabel_2")
        self.Back_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Back_Button.setGeometry(QtCore.QRect(110, 120, 61, 23))
        self.Back_Button.setObjectName("Back_Button")
        self.Pre_hight_label = QtWidgets.QLabel(self.centralwidget)
        self.Pre_hight_label.setGeometry(QtCore.QRect(190, 270, 61, 16))
        self.Pre_hight_label.setObjectName("Pre_hight_label")
        self.Head_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Head_Button.setGeometry(QtCore.QRect(20, 120, 61, 23))
        self.Head_Button.setObjectName("Head_Button")
        self.Start_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Start_Button.setGeometry(QtCore.QRect(90, 320, 71, 21))
        self.Start_Button.setObjectName("Start_Button")
        self.Hight_Edit = QtWidgets.QLineEdit(self.centralwidget)
        self.Hight_Edit.setGeometry(QtCore.QRect(80, 270, 91, 21))
        self.Hight_Edit.setObjectName("Hight_Edit")
        self.Pre_speed_label = QtWidgets.QLabel(self.centralwidget)
        self.Pre_speed_label.setGeometry(QtCore.QRect(190, 190, 61, 16))
        self.Pre_speed_label.setObjectName("Pre_speed_label")
        self.Higth_label = QtWidgets.QLabel(self.centralwidget)
        self.Higth_label.setGeometry(QtCore.QRect(20, 272, 54, 20))
        self.Higth_label.setObjectName("Higth_label")
        self.Drop_Button = QtWidgets.QPushButton(self.centralwidget)
        self.Drop_Button.setGeometry(QtCore.QRect(270, 150, 75, 23))
        self.Drop_Button.setObjectName("Drop_Button")
        self.IP_lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.IP_lineEdit.setGeometry(QtCore.QRect(60, 10, 151, 21))
        self.IP_lineEdit.setObjectName("IP_lineEdit")
        self.Status_label = QtWidgets.QLabel(self.centralwidget)
        self.Status_label.setGeometry(QtCore.QRect(20, 90, 41, 16))
        self.Status_label.setObjectName("Status_label")
        self.show_status_label = QtWidgets.QLabel(self.centralwidget)
        self.show_status_label.setGeometry(QtCore.QRect(60, 80, 131, 21))
        self.show_status_label.setText("")
        self.show_status_label.setObjectName("show_status_label")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 374, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Pre_hight_Edit.setText(_translate("MainWindow", "0.0  mm"))
        self.Lift_Button.setText(_translate("MainWindow", "油泵抬升"))
        self.Port_lineEdit.setText(_translate("MainWindow", "8089"))
        self.Pre_angel_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">当前角度</span></p></body></html>"))
        self.Stop_Button.setText(_translate("MainWindow", "停止"))
        self.IPlabel.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">IP:</span></p></body></html>"))
        self.Disconnect_Button.setText(_translate("MainWindow", "断开"))
        self.Speed_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">发送速度</span></p></body></html>"))
        self.Right_Button.setText(_translate("MainWindow", "右转"))
        self.Angle_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">发送角度</span></p></body></html>"))
        self.Pre_speed_Edit.setText(_translate("MainWindow", "0.00    m/s"))
        self.Connect_Button.setWhatsThis(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">连接</span></p></body></html>"))
        self.Connect_Button.setText(_translate("MainWindow", "连接"))
        self.Pre_angle_Edit.setText(_translate("MainWindow", "0.00  度"))
        self.Left_Button.setText(_translate("MainWindow", "左转"))
        self.IPlabel_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">端口：</span></p></body></html>"))
        self.Back_Button.setText(_translate("MainWindow", "后退"))
        self.Pre_hight_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">当前高度</span></p></body></html>"))
        self.Head_Button.setText(_translate("MainWindow", "前进"))
        self.Start_Button.setText(_translate("MainWindow", "运行"))
        self.Pre_speed_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">当前速度</span></p></body></html>"))
        self.Higth_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:10pt; font-weight:600;\">发送高度</span></p></body></html>"))
        self.Drop_Button.setText(_translate("MainWindow", "油泵下降"))
        self.IP_lineEdit.setText(_translate("MainWindow", "192.168.0.20"))
        self.Status_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">状态：</span></p></body></html>"))

